defmodule MetricsDspyParityTest do
  @moduledoc """
  Differential parity for answer normalization and metrics against REAL DSPy
  3.2.1 (dee-c2ur, dee-j11u, epic dee-zobd).

  Expected values in test/fixtures/metrics_parity/cases.json were generated by
  running dspy.evaluate.metrics (normalize_text / em_score / f1_score /
  hotpot_f1_score / _passage_match) inside the pinned parity venv:

      tmp/dspy-parity-venv/bin/python scripts/dspy_metrics_differential.py

  The table run must assert BYTE-identical normalization (NFD forms and
  combining marks included) and equal EM/F1/passage verdicts. The pre-fix
  normalize_text (punctuation replaced with spaces, no NFD) fails this table
  on every punctuated or accented case.
  """

  use ExUnit.Case, async: true

  @fixture_path Path.expand("fixtures/metrics_parity/cases.json", __DIR__)
  @python "tmp/dspy-parity-venv/bin/python"
  @generator "scripts/dspy_metrics_differential.py"

  defp fixture do
    @fixture_path |> File.read!() |> Jason.decode!()
  end

  test "normalize_text matches DSPy byte-for-byte on every adversarial case" do
    cases = fixture()["normalize_cases"]
    assert length(cases) >= 25

    failures =
      for %{"id" => id, "input" => input, "expected" => expected} <- cases,
          actual = Imp.Metrics.normalize_text(input),
          actual != expected do
        {id, input, actual, expected}
      end

    assert failures == [],
           "Imp normalize_text diverges from DSPy on:\n" <>
             Enum.map_join(failures, "\n", fn {id, input, actual, expected} ->
               "  #{id}: input=#{inspect(input)} imp=#{inspect(actual)} dspy=#{inspect(expected)}"
             end)
  end

  test "em/f1/hotpot_f1 match DSPy scores on every gold/pred pair" do
    for %{"id" => id, "prediction" => pred, "gold" => gold} = row <- fixture()["pair_cases"] do
      assert Imp.Metrics.em(pred, gold) == row["em"],
             "#{id}: em(#{inspect(pred)}, #{inspect(gold)}) != DSPy #{row["em"]}"

      imp_f1 = Imp.Metrics.f1(pred, gold)

      assert_in_delta imp_f1, row["f1"], 1.0e-12, "#{id}: f1 imp=#{imp_f1} dspy=#{row["f1"]}"

      imp_hotpot = Imp.Metrics.hotpot_f1(pred, gold)

      assert_in_delta imp_hotpot,
                      row["hotpot_f1"],
                      1.0e-12,
                      "#{id}: hotpot_f1 imp=#{imp_hotpot} dspy=#{row["hotpot_f1"]}"
    end
  end

  test "passage_match matches DSPy DPR has_answer verdicts" do
    for %{"id" => id, "answers" => answers, "passages" => passages} = row <-
          fixture()["passage_cases"] do
      assert Imp.Metrics.passage_match(passages, answers) == row["match"],
             "#{id}: passage_match(#{inspect(passages)}, #{inspect(answers)}) != DSPy #{row["match"]}"
    end
  end

  test "answer_passage_match factory applies DPR semantics to example/prediction pairs" do
    metric = Imp.Metrics.answer_passage_match()

    # The wave-1 defect probe: "art" must NOT match inside "participated".
    example = Imp.example(answer: "art")
    prediction = Imp.prediction(context: ["Many participated in the event"])
    refute metric.(example, prediction)

    # Per-passage iteration: hit in the second passage passes.
    example = Imp.example(answer: "Paris")
    prediction = Imp.prediction(context: ["nothing here", "He lives in Paris now"])
    assert metric.(example, prediction)

    # No match across the passage seam (the old concatenation defect).
    example = Imp.example(answer: "New York City")
    prediction = Imp.prediction(context: ["He moved to New York", "City taxes are high"])
    refute metric.(example, prediction)

    # A bare string context counts as a single passage.
    example = Imp.example(answer: "Eiffel Tower")
    prediction = Imp.prediction(context: "The Eiffel Tower is in Paris.")
    assert metric.(example, prediction)
  end

  test "official HotPotQA regression pinned by dee-j11u: the U.S. congress probe" do
    # The keys official_hotpotqa_f1/em claim the official metric, so the
    # official value must hold: DSPy f1_score('the US congress','U.S. congress')
    # == 1.0 (the pre-fix home-grown normalization scored this 0.4).
    assert Imp.Metrics.f1("the US congress", "U.S. congress") == 1.0
    assert Imp.Metrics.hotpot_f1("the US congress", "U.S. congress") == 1.0
    assert Imp.Metrics.em("the US congress", "U.S. congress") == true

    # Official HotPotQA yes/no/noanswer gating (hotpot_evaluate_v1.py, ported
    # by DSPy hotpot_f1_score): mismatched special labels score 0 even with
    # token overlap.
    assert Imp.Metrics.hotpot_f1("noanswer", "no answer") == 0.0
    assert Imp.Metrics.hotpot_f1("yes", "no") == 0.0
  end

  @tag :evidence_infrastructure
  @tag :requires_dspy_capture
  test "committed fixture is fresh against the pinned DSPy parity venv" do
    unless File.exists?(@python) do
      flunk("missing #{@python}; run scripts/setup_dspy_parity_env.sh")
    end

    out_dir = Path.join(System.tmp_dir!(), "metrics-parity-#{System.unique_integer([:positive])}")
    File.mkdir_p!(out_dir)
    out_path = Path.join(out_dir, "cases.json")

    try do
      {output, status} =
        System.cmd(Path.expand(@python), [Path.expand(@generator), out_path],
          stderr_to_stdout: true
        )

      assert status == 0, "generator failed:\n#{output}"

      fresh = out_path |> File.read!() |> Jason.decode!()
      committed = fixture()

      assert fresh == committed,
             "test/fixtures/metrics_parity/cases.json is stale; regenerate with " <>
               "#{@python} #{@generator}"
    after
      File.rm_rf!(out_dir)
    end
  end
end
